set positional-arguments
set fallback
set shell := ["bash", "-cue"]

host_name := "vm-nix-cache"

# Deploy Commands =============================================================
default:
    just --list --unsorted

# Build the VM.
build:
    nix build -L ".#nixosConfigurations.{{host_name}}.config.system.build.toplevel"
