set positional-arguments
set fallback
set shell := ["bash", "-cue"]

host_name := "vm-ordes-main"

# Deploy Commands =============================================================
default:
    just --list --unsorted

# Build the VM.
build:
    nix build -L ".#nixosConfigurations.{{host_name}}.config.system.build.toplevel"

test-vm:
    #!/usr/bin/env bash
    set -eu -o pipefail
    root_dir=$(git rev-parse --show-toplevel)
    . "$root_dir/tools/scripts/general.sh"

    nix run github:nix-community/nixos-anywhere -- \
        --flake "#vm-ordes-main" --vm-test --show-trace
