apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../common/operators/gateway-api-crds/
  - ../../../../../common/operators/cloudnative-pg/
  - ../../../../../common/operators/traefik/
  - letsencrypt.yaml

patches:
  - path: traefik.yaml
